/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package olc.practica1_201801229.Forms;
import java.util.ArrayList;
import Clases.*;
import static olc.practica1_201801229.OLCPractica1_201801229.listaExpresiones;
import static olc.practica1_201801229.OLCPractica1_201801229.listaLexemas;
import static olc.practica1_201801229.OLCPractica1_201801229.listaNodos;
import static olc.practica1_201801229.OLCPractica1_201801229.listaConjunto;
import static olc.practica1_201801229.OLCPractica1_201801229.funciono;
/**
 *
 * @author jkamg
 */
public class Analizador_Lexico extends javax.swing.JFrame {

    /**
     * Creates new form Analizador_Lexico
     */
    public Analizador_Lexico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Entrada = new java.awt.TextArea();
        label1 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Salida = new java.awt.TextArea();
        label2 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));
        getContentPane().add(Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 360, 340));

        label1.setText("Archivo de Entrada");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jButton1.setText("Analizar Entrada");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        jButton3.setText("Generar Automata");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));
        getContentPane().add(Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 1040, 120));

        label2.setText("Salida");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 160, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arboles", "Siguientes", "Transiciones", "Automatas" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 120, -1));
        jComboBox1.getAccessibleContext().setAccessibleName("ComoboBoxOpciones");

        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 430, 270));
        jLabel1.getAccessibleContext().setAccessibleName("Imagenes");

        jButton2.setText("Anterior");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, -1, -1));

        jButton4.setLabel("Siguiente");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 410, -1, -1));

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Guardar Como...");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        listaConjunto = null;
        listaConjunto=new ArrayList<Conjunto>();
        listaLexemas = null;
        listaLexemas=new ArrayList<LexemaEntrada>();
        listaExpresiones = null;
        listaExpresiones=new ArrayList<ExpresionesRegulares>();
        funciono = true;
        String texto = Entrada.getText();
        AnalizadorLexico analizar = new AnalizadorLexico();
        analizar.analizar(texto);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (funciono == true) {
            String expresiones = "Expresiones: \n";
        for (ExpresionesRegulares er : listaExpresiones) {
            if (er!=null) {
                expresiones += "Nombre: " + er.getNombre() + " Expresion: " + er.getExpresionRegular() + "\n";
            }
        }
        String lexemas = "Lexemas: \n";
        for (LexemaEntrada le : listaLexemas) {
            if (le!=null) {
                lexemas += "Nombre: " + le.getNombre() + " Lexema: " + le.getLexema() + "\n";
            }
        }
        String conjuntos = "Conjuntos: \n";
        for (Conjunto c : listaConjunto) {
            if (c!=null) {
                conjuntos += "Nombre: " + c.getNombre() + " Elementos: ";
                if (c.isEstado()==true) {
                    for (Object o : c.getElementos()) {
                        if (o!=null) {
                            conjuntos += o.toString() +", ";
                        }
                    }
                }else{
                    for (Object o : c.getElementos()) {
                        if (o!=null) {
                            conjuntos += o.toString() +"~";
                        }
                    }
                }
                conjuntos += "\n";
            }
        }
        String todo = expresiones + lexemas + conjuntos +"\n";
        GeneradorArbol ga = new GeneradorArbol();
        String tod1 = todo;
        Salida.setText(ga.grafica());
        
        }else {
            Salida.setText("Cagadas no funciono");
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea Entrada;
    private java.awt.TextArea Salida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
